### ISSUE TITLE
Group schema components by content-type

### ISSUE THREAD

**Issue by souenzzo** [OAI/Documentation#141]
I'm working on an API that has many content-type, and they use references to schema

The references to the `user` entity, for example, aren't the same on each content-type.

I'm currently handling that by adding a content-type prefix on each schema:

```yaml
schemas:
  application/json_user:
    type: object
  application/custom+json_user:
    type: object
```

I'd like to use something like

```yaml
schemas:
  application/json:
    user:
      ...
  application/custom+json:
    user:
      ...
```
