### ISSUE TITLE
inconsistency between documentation and spec: is paths required?

### ISSUE THREAD

**Issue by karenetheridge** [OAI/Documentation#25]
in https://github.com/OAI/Documentation/blob/main/specification-structure.md:

> The root object in any OpenAPI document is the OpenAPI Object and only three of its fields are mandatory: openapi, info and paths.

But the schema (https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.yaml) says:

```
anyOf:
  - required:
    - paths
  - required:
    - components
  - required:
    - webhooks
```

Which one is correct?
